### PR TITLE
show code plugin fix

### PR DESCRIPTION
**Pull request by lpylpyleo**
Describe what problem this pull request solves and how to solve it. If there is an issue associated with it, please attach a link.

请描述这个 pull request 解决了什么问题，以及解决方式。如果有与之关联的 issue，请附链接。

- typo fix: `CodeDisplatService` => `CodeDisplayService `
- 修复遍历查找没有正确break
- `getIdWithClassName ` 这个方法没有用参数`className`
- 改善测试用例

## Pull Request Checklist

- [x] I have read the [UME contribution document](../CONTRIBUTING.md) and understand how to contribute, commit the code according to the rules. 我已阅读过 UME 贡献文档，并了解如何进行贡献，按照规则提交了代码
- [x] I have added the necessary comments in code to ensure that other contributors can understand the reason for the change. 我在修改中已经添加了必要的注释，以确保便于其他贡献者理解修改原因
- [x] The code has been formatted by dartfmt before push. 代码在提交前已经经过 dartfmt 进行了格式化
- [x] Change does not involve the adjustment of test cases. Or all existing and new tests are passing. 改动不涉及测试用例调整，或 example 工程与单元测试已经完全跑通

If you need help, consider [Join ing the ByteDance Flutter Exchange Group](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=67au2f75-3783-41b0-8868-0fc0178f1fd8).

如有任何问题，可以[加入字节跳动 Flutter 交流群](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=67au2f75-3783-41b0-8868-0fc0178f1fd8)。

Or contact [author](mailto:zhaorui.dev@bytedance.com).

或随时[联系开发者](mailto:zhaorui.dev@bytedance.com)。

原来的查找方法存在的问题：

```dart
void main(List<String> args) {
  final List<int>? list = [1, 2, 3, 4, 5];
  int? result;
  list?.forEach((element) {
    print('current: $element');
    if (element.isEven) {
      result = element;
      return;
    }
  });
  print('result: $result');
}
}
```

output:
```
current: 1
current: 2
current: 3
current: 4
current: 5
result: 4
```

原来的commit弄乱了，采用这个request

### CODE REVIEW

**Review by talisk — APPROVED** [review]
LGTM

**Review by smileShirely — APPROVED** [review]
LGTM

**Comment by lpylpyleo** [comment]
It seems that the `flutter_coverage_badge` package in `pubspec.yaml` cannot be downloaded in github workflow. Is there a public key available? Or can we use http download?

```
ERR : Git error. Command: `git clone --mirror git@github.com:amondnet/flutter_coverage_badge.git /opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/git/cache/flutter_coverage_badge-2cd592521b294eaf4d31157cf4fa08a73785ca2b`
    | stdout: 
    | stderr: Cloning into bare repository '/opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/git/cache/flutter_coverage_badge-2cd592521b294eaf4d31157cf4fa08a73785ca2b'...
    | git@github.com: Permission denied (publickey).
    | fatal: Could not read from remote repository.
    | 
    | Please make sure you have the correct access rights
    | and the repository exists.
    | exit code: 128
```

**Comment by smileShirely** [comment]
> It seems that the `flutter_coverage_badge` package in `pubspec.yaml` cannot be downloaded in github workflow. Is there a public key available? Or can we use http download?
> 
> ```
> ERR : Git error. Command: `git clone --mirror git@github.com:amondnet/flutter_coverage_badge.git /opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/git/cache/flutter_coverage_badge-2cd592521b294eaf4d31157cf4fa08a73785ca2b`
>     | stdout: 
>     | stderr: Cloning into bare repository '/opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/git/cache/flutter_coverage_badge-2cd592521b294eaf4d31157cf4fa08a73785ca2b'...
>     | git@github.com: Permission denied (publickey).
>     | fatal: Could not read from remote repository.
>     | 
>     | Please make sure you have the correct access rights
>     | and the repository exists.
>     | exit code: 128
> ```

I noticed this problem. I thought about it, this should be because GitHub Actions does not have a publickey. And the flutter_coverage_badge was dependent by git ssh url. I changed it to a https url and commit to `bytedance:develop_nullsafety` branch. You can merge `bytedance:develop_nullsafety` branch and retry.

**Comment by lpylpyleo** [comment]
> > It seems that the `flutter_coverage_badge` package in `pubspec.yaml` cannot be downloaded in github workflow. Is there a public key available? Or can we use http download?
> > ```
> > ERR : Git error. Command: `git clone --mirror git@github.com:amondnet/flutter_coverage_badge.git /opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/git/cache/flutter_coverage_badge-2cd592521b294eaf4d31157cf4fa08a73785ca2b`
> >     | stdout: 
> >     | stderr: Cloning into bare repository '/opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/git/cache/flutter_coverage_badge-2cd592521b294eaf4d31157cf4fa08a73785ca2b'...
> >     | git@github.com: Permission denied (publickey).
> >     | fatal: Could not read from remote repository.
> >     | 
> >     | Please make sure you have the correct access rights
> >     | and the repository exists.
> >     | exit code: 128
> > ```
> 
> I noticed this problem. I thought about it, this should be because GitHub Actions does not have a publickey. And the flutter_coverage_badge was dependent by git ssh url. I changed it to a https url and commit to `bytedance:develop_nullsafety` branch. You can merge `bytedance:develop_nullsafety` branch and retry.

It was pushed to master and it keeps failing.

**Comment by smileShirely** [comment]
> > > It seems that the `flutter_coverage_badge` package in `pubspec.yaml` cannot be downloaded in github workflow. Is there a public key available? Or can we use http download?
> > > ```
> > > ERR : Git error. Command: `git clone --mirror git@github.com:amondnet/flutter_coverage_badge.git /opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/git/cache/flutter_coverage_badge-2cd592521b294eaf4d31157cf4fa08a73785ca2b`
> > >     | stdout: 
> > >     | stderr: Cloning into bare repository '/opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/git/cache/flutter_coverage_badge-2cd592521b294eaf4d31157cf4fa08a73785ca2b'...
> > >     | git@github.com: Permission denied (publickey).
> > >     | fatal: Could not read from remote repository.
> > >     | 
> > >     | Please make sure you have the correct access rights
> > >     | and the repository exists.
> > >     | exit code: 128
> > > ```
> > 
> > 
> > I noticed this problem. I thought about it, this should be because GitHub Actions does not have a publickey. And the flutter_coverage_badge was dependent by git ssh url. I changed it to a https url and commit to `bytedance:develop_nullsafety` branch. You can merge `bytedance:develop_nullsafety` branch and retry.
> 
> It was pushed to master and it keeps failing.

Sorry... Because the `flutter_coverage_badge` depends on `lcov.dart` uses the git protocol dependency. Now I fixed it. Could you try it again?
https://github.com/bytedance/flutter_ume/actions/runs/1096250856

**Comment by lpylpyleo** [comment]
I'm not sure what I should do. Should I merge the master branch and then push? @smileShirely 
1. chechout master
2. git pull
3. checkout my branch (lpylpyleo:show_code_fix_nullsafety2)
4. git merge master
5. git push
These steps will cause extra commits again

**Comment by smileShirely** [comment]
> I'm not sure what I should do. Should I merge the master branch and then push? @smileShirely
> 
> 1. chechout master
> 2. git pull
> 3. checkout my branch (lpylpyleo:show_code_fix_nullsafety2)
> 4. git merge master
> 5. git push
>    These steps will cause extra commits again

Your branch is based on `bytedance:develop_nullsafety`, so you should merge `develop_nullsafety` to your branch. I have pushed the `flutter_coverate_badge` dependency change to `develop_nullsafety` branch.

**Pull request merged**
